print('Rooz Bekheyr')
print ( 'lotfan baraye mohasebe masahat mosalas argham khaste shode ra vared konid . ')
print ('--------------------------------------------------------------------------------')
print ('Ertefae mosalas ra vared konid ?')
Ertefae = int(input())
print ('--------------------')
print('Tool ghaeede mosalas ra vared konid ?')
Tool_ghaeede = int (input())
print ('Javab =')
print ((Ertefae*Tool_ghaeede)/2)
