print('Rooz Bekheyr')
print (             )
print ( 'Yek adad 6 raghami vared konid , ta magmooe ragham dovom va panjom an ra begooyim')
print ('--------------------------------------------------------------------------------')
print ('Adad 6 raghami ra vared konid ?')
Adad = int (input())
print ('--------------------')
Adad2 = int ( Adad % 100000 // 10000) 
Adad3 = int ( Adad % 100 // 10) 
print ("Magmooee =")
print (              )
print (Adad2+Adad3)