print('Rooz Bekheyr')
print ( 'lotfan baraye mohasebe masahat kole va masahat janebi va hajm ostovane argham khaste shode ra vared konid . ')
print ('--------------------------------------------------------------------------------')
print ('Ertefae ostovane ra vared konid ?')
Ertefae = float(input())
print ('--------------------')
print('shoaae ostovane ra vared konid ?')
shoaae = float (input())
MJ=(2*3.4*shoaae*Ertefae)
MK = (2*3.4*shoaae**2+2*3.4*shoaae*Ertefae)
H = (3.4*shoaae**2*Ertefae)
print ('--------------------')
print ('Masahat kole =')
print(MK)
print ('               ')
print('masahat janebi =')
print(MJ)
print ('               ')
print('hajm =')
print (H)
