print('Rooz Bekheyr')
print('                  ')
print ( 'Soraat mashin khod ra bar hasbe mailes vard konid . ')
print ('--------------------------------------------------------------------------------')
print (' soraat ra vared konid ?')
soraat = int(input())
soraat_k = float (1.6093*soraat)
print ('Soraat Bar hasbe kilometr = ' )
print (soraat_k)